# Generated by Django 2.1.7 on 2019-03-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='regestrationnumber',
            new_name='user',
        ),
    ]
