# Generated by Django 2.1.7 on 2019-03-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190308_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='library',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
