# Generated by Django 2.1.7 on 2019-03-10 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=20)),
                ('inst', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
