# Generated by Django 2.1.7 on 2019-03-18 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20190318_2005'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hwincourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.CharField(max_length=20)),
                ('instructorname', models.CharField(max_length=20)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('superviser', models.CharField(max_length=20)),
                ('question', models.ManyToManyField(to='challenges.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='studentincourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.CharField(max_length=20)),
                ('studentName', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='inst',
        ),
        migrations.AddField(
            model_name='course',
            name='instructorname',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
