# Generated by Django 2.1.7 on 2019-03-21 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0005_auto_20190318_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinstructure',
            old_name='courseName',
            new_name='courseid',
        ),
        migrations.RemoveField(
            model_name='hwincourse',
            name='id',
        ),
        migrations.AddField(
            model_name='hwincourse',
            name='descreption',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hwincourse',
            name='hwname',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hwincourse',
            name='courseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='studentincourse',
            name='courseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.RemoveField(
            model_name='studentincourse',
            name='studentName',
        ),
        migrations.AddField(
            model_name='studentincourse',
            name='studentName',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
