# Generated by Django 2.1.7 on 2019-03-12 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagetestcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Input', models.ImageField(upload_to='')),
                ('output', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='texttestcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Input', models.TextField()),
                ('output', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challengeName',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='texttestcase',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge', to_field='challengeName'),
        ),
        migrations.AddField(
            model_name='imagetestcase',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge', to_field='challengeName'),
        ),
    ]
