# Generated by Django 2.1.7 on 2019-03-17 16:42

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20190312_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetestcase',
            name='Input',
            field=models.ImageField(upload_to=challenges.models.upload_input_challenge),
        ),
    ]
