# Generated by Django 2.1.7 on 2019-03-18 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20190317_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='courseid',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='id',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challengeName',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='imagetestcase',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge'),
        ),
        migrations.AlterField(
            model_name='texttestcase',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge'),
        ),
    ]
